CREATE OR REPLACE TABLE DIA.F_VALORISATION_SUPPORT_CONTRAT_ (
    SK_F_VALORISATION_SUPPORT_CONTRAT_ NUMBER(38,0) NOT NULL AUTOINCREMENT,
    ID_SUPPORT_COMPOSANT NUMBER,
    DT_VALORISATION TIMESTAMP_NTZ,
    DT_SITUATION_CONTRAT TIMESTAMP_NTZ,
    DT_FIN_VALORISATION TIMESTAMP_NTZ,
    PLUS_OU_MOINS_VALUE NUMBER(38,10),
    MT_SUPPORT NUMBER(38,10),
    NB_PART NUMBER(38,10),
    ID_SUPPORT_RETRAITE NUMBER,
    FK_D_SUPPORT_RETRAITE NUMBER,
    EST_DERNIERE_SITUATION BOOLEAN,
    ID_CONTRAT NUMBER,
    FK_D_CONTRAT_RETRAITE NUMBER,
    FK_D_CONTRAT_RETRAITE_DERNIERE_VERSION NUMBER,
    ID_PROFIL_GESTION NUMBER,
    FK_D_PROFIL_GESTION_RETRAITE NUMBER,
    DT_CREA TIMESTAMP_NTZ,
    DT_MODIF TIMESTAMP_NTZ,
    DT_ALIM TIMESTAMP_NTZ,
    CONSTRAINT PK_F_VALORISATION_SUPPORT_CONTRAT_ PRIMARY KEY (SK_F_VALORISATION_SUPPORT_CONTRAT_),
    CONSTRAINT UK_F_VALORISATION_SUPPORT_CONTRAT_ UNIQUE (
        ID_SUPPORT_COMPOSANT,
        DT_VALORISATION,
        DT_SITUATION_CONTRAT,
        DT_FIN_VALORISATION
    ),
    CONSTRAINT FK_FVSC_SUPPORT_RETRAITE FOREIGN KEY (FK_D_SUPPORT_RETRAITE)
        REFERENCES DIA.D_SUPPORT_RETRAITE (SK_D_SUPPORT_RETRAITE),
    CONSTRAINT FK_FVSC_CONTRAT_RETRAITE FOREIGN KEY (FK_D_CONTRAT_RETRAITE)
        REFERENCES DIA.D_CONTRAT_RETRAITE (SK_D_CONTRAT_RETRAITE),
    CONSTRAINT FK_FVSC_CONTRAT_RET_DERNIERE FOREIGN KEY (FK_D_CONTRAT_RETRAITE_DERNIERE_VERSION)
        REFERENCES DIA.D_CONTRAT_RETRAITE (SK_D_CONTRAT_RETRAITE),
    CONSTRAINT FK_FVSC_PROFIL_GESTION FOREIGN KEY (FK_D_PROFIL_GESTION_RETRAITE)
        REFERENCES DIA.D_PROFIL_GESTION_RETRAITE (SK_D_PROFIL_GESTION_RETRAITE)
);
