INSERT ALL 
WHEN (SELECT NOT EXISTS (SELECT * FROM DIA.F_EVENEMENT_RETRAITE WHERE SK_F_EVENEMENT_RETRAITE = 0)) 
THEN INTO DIA.F_EVENEMENT_RETRAITE (SK_F_EVENEMENT_RETRAITE, ID_EVENEMENT, CD_STATUT, DT_MODIFICATION, DT_EFFET, PLUS_VALUE_TAXABLE, PRELEVEMENT_FISCAUX, PRELEVEMENT_SOCIAUX, TX_FRAIS_EVENEMENT, ID_CONTRAT, FK_D_CONTRAT_RETRAITE, FK_D_CONTRAT_RETRAITE_DERNIERE_VERSION, CD_EVENEMENT, FK_D_EVENEMENT_RETRAITE, DT_CREA, DT_MODIF, DT_ALIM) 
VALUES (0, 0, GETDATE(), GETDATE(), GETDATE(), 0, 0, 0, 0, 0, 0, 0, '0', 0, GETDATE(), GETDATE(), GETDATE()) 
WHEN (SELECT NOT EXISTS (SELECT * FROM DIA.F_EVENEMENT_RETRAITE WHERE SK_F_EVENEMENT_RETRAITE = -1)) 
THEN INTO DIA.F_EVENEMENT_RETRAITE (SK_F_EVENEMENT_RETRAITE, ID_EVENEMENT, CD_STATUT, DT_MODIFICATION, DT_EFFET, PLUS_VALUE_TAXABLE, PRELEVEMENT_FISCAUX, PRELEVEMENT_SOCIAUX, TX_FRAIS_EVENEMENT, ID_CONTRAT, FK_D_CONTRAT_RETRAITE, FK_D_CONTRAT_RETRAITE_DERNIERE_VERSION, CD_EVENEMENT, FK_D_EVENEMENT_RETRAITE, DT_CREA, DT_MODIF, DT_ALIM) 
VALUES (-1, -1, GETDATE(), GETDATE(), GETDATE(), -1, -1, -1, -1, -1, -1, -1, '-1', -1, GETDATE(), GETDATE(), GETDATE()) SELECT * FROM DUAL;