INSERT ALL 
WHEN (SELECT NOT EXISTS (SELECT * FROM DIA.F_VALORISATION_SUPPORT_CONTRAT_RETRAITE WHERE SK_F_VALORISATION_SUPPORT_CONTRAT_RETRAITE = 0)) 
THEN INTO DIA.F_VALORISATION_SUPPORT_CONTRAT_RETRAITE (SK_F_VALORISATION_SUPPORT_CONTRAT_RETRAITE, ID_SUPPORT_COMPOSANT, DT_VALORISATION, DT_SITUATION_CONTRAT, DT_FIN_VALORISATION, PLUS_OU_MOINS_VALUE, MT_SUPPORT, NB_PART, ID_SUPPORT_RETRAITE, FK_D_SUPPORT_RETRAITE, EST_DERNIERE_SITUATION, ID_CONTRAT, FK_D_CONTRAT_RETRAITE, FK_D_CONTRAT_RETRAITE_DERNIERE_VERSION, ID_PROFIL_GESTION, FK_D_PROFIL_GESTION_RETRAITE, DT_CREA, DT_MODIF, DT_ALIM) 
VALUES (0, 0, GETDATE(), GETDATE(), GETDATE(), 0, 0, 0, 0, 0, '0', 0, 0, 0, 0, 0, GETDATE(), GETDATE(), GETDATE()) 
WHEN (SELECT NOT EXISTS (SELECT * FROM DIA.F_VALORISATION_SUPPORT_CONTRAT_RETRAITE WHERE SK_F_VALORISATION_SUPPORT_CONTRAT_RETRAITE = -1)) 
THEN INTO DIA.F_VALORISATION_SUPPORT_CONTRAT_RETRAITE (SK_F_VALORISATION_SUPPORT_CONTRAT_RETRAITE, ID_SUPPORT_COMPOSANT, DT_VALORISATION, DT_SITUATION_CONTRAT, DT_FIN_VALORISATION, PLUS_OU_MOINS_VALUE, MT_SUPPORT, NB_PART, ID_SUPPORT_RETRAITE, FK_D_SUPPORT_RETRAITE, EST_DERNIERE_SITUATION, ID_CONTRAT, FK_D_CONTRAT_RETRAITE, FK_D_CONTRAT_RETRAITE_DERNIERE_VERSION, ID_PROFIL_GESTION, FK_D_PROFIL_GESTION_RETRAITE, DT_CREA, DT_MODIF, DT_ALIM) 
VALUES (-1, -1, GETDATE(), GETDATE(), GETDATE(), -1, -1, -1, -1, -1, '-1', -1, -1, -1, -1, -1, GETDATE(), GETDATE(), GETDATE()) 
SELECT * FROM DUAL;
