CREATE OR REPLACE TABLE DIA.D_ASSURE_RETRAITE (
    SK_D_ASSURE_RETRAITE          NUMBER(38,0)       NOT NULL autoincrement,
    ID_ASSURE                     VARCHAR(16777216)  NOT NULL,
    ID_PERSONNE_ASSURE            NUMBER(38,0),
    FK_D_PERSONNE_RETRAITE_ASSURE NUMBER(38,0),
    ID_CONTRAT_RETRAITE           NUMBER(38,0),
    FK_D_CONTRAT_RETRAITE         NUMBER(38,0),
    DT_CREA                       TIMESTAMP_NTZ(9),
    DT_MODIF                      TIMESTAMP_NTZ(9),
    DT_ALIM                       TIMESTAMP_NTZ(9),
    CONSTRAINT PK_D_ASSURE_RETRAITE PRIMARY KEY (SK_D_ASSURE_RETRAITE),
    CONSTRAINT UK_D_ASSURE_RETRAITE UNIQUE (ID_ASSURE)
);
